harambee/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from harambee.settings import MEDIA_URL, MEDIA_ROOT
from harambee.views import PageView, HelpPageView, LoginView, JoinView, ProfileView, MenuView, \
    CompletedModuleView, HomeView, ModuleHomeView, JourneyHomeView, ForgotPinView, \
    ChangePinView, ChangeMobileNumberView, LevelIntroView, ModuleEndView, \
    LevelEndView, QuestionView, RightView, WrongView, IntroView, HelpView, LogoutView, CustomSearchView, ContactView, \
    DeleteSMSView, SendSMSView


urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^menu/$', MenuView.as_view(), name='misc.menu'),

                       url(r'^$', RedirectView.as_view(url="/welcome", permanent=True)),

                       url(r'^join/$', JoinView.as_view(), name='auth.join'),
                       url(r'^login/$', LoginView.as_view(), name='auth.login'),
                       url(r'^logout/$', LogoutView.as_view(), name='auth.logout'),
                       url(r'^forgot_pin/$', ForgotPinView.as_view(), name='auth.forgot_pin'),
                       url(r'^profile/$', ProfileView.as_view(), name='auth.profile'),
                       url(r'^change_number/$', ChangeMobileNumberView.as_view(), name='auth.change_number'),
                       url(r'^change_pin/$', ChangePinView.as_view(), name='auth.change_pin'),

                       url(r'^intro/$', IntroView.as_view(), name='misc.intro'),
                       url(r'^help/$', HelpView.as_view(), name='misc.help'),

                       url(r'^home/$', HomeView.as_view(), name='content.home'),
                       url(r'^journey_home/(?P<slug>[-\w]+)/$', JourneyHomeView.as_view(), name='content.journey_home'),
                       url(r'^completed_modules/$', CompletedModuleView.as_view(), name='content.completed_modules'),
                       url(r'^module_home/(?P<journey_slug>[-\w]+)/(?P<module_slug>[-\w]+)/$',
                           ModuleHomeView.as_view(), name='content.module_home'),
                       url(r'^module_end/(?P<journey_slug>[-\w]+)/(?P<module_slug>[-\w]+)/$', ModuleEndView.as_view(),
                           name='content.module_end'),
                       url(r'^level_intro/(?P<journey_slug>[-\w]+)/(?P<module_slug>[-\w]+)/(?P<pk>[0-9]+)/$',
                           LevelIntroView.as_view(), name='content.level_intro'),
                       url(r'^level_end/$', LevelEndView.as_view(), name='content.level_end'),
                       url(r'^question/$', QuestionView.as_view(), name='content.question'),
                       url(r'^right/$', RightView.as_view(), name='content.right'),
                       url(r'^wrong/$', WrongView.as_view(), name='content.wrong'),

                       url(r'^search/', CustomSearchView(), name='misc.search'),

                       url(r'^contact/$', ContactView.as_view(), name='misc.contact'),

                       url(r'^harambee/send_sms/(?P<ids>(\d+)(,\d+)*)/$', SendSMSView.as_view(), name='admin.send_sms'),

                       url(r'^sms/delete/(?P<ids>(\d+)(,\d+)*)/$', DeleteSMSView.as_view(), name='admin.delete_sms'),

                       url(r'^(?P<slug>[-\w]+)/$', PageView.as_view()),
                       url(r'^help/(?P<slug>[-\w]+)/$', HelpPageView.as_view()),

                       url(r'^djga/', include('google_analytics.urls')),
                       ) + static(MEDIA_URL, document_root=MEDIA_ROOT)

content/models.py
from django.db.models import Count
from django.utils import timezone
from django.db import models
from colorful.fields import RGBColorField


class Journey(models.Model):

    name = models.CharField("Name", max_length=500, blank=False, unique=True)
    intro_text = models.TextField("Introductory Text", blank=True)
    slug = models.SlugField("Slug", unique=True, help_text="Slug used to identify this journey in URL. Must be unique."
                                                           "e.g. Journey_101")
    title = models.CharField("Title", max_length=500, blank=False, help_text="Title is displayed in the browsers tab.")
    show_menu = models.BooleanField("Show in menus", default=True, help_text="Show the journey link in users menu?")
    search = models.CharField("Search description", max_length=500)
    image = models.ImageField("Image", upload_to="journeys/", blank=True, null=True,
                              help_text="This is an icon and the ideal size for this icon is 32 x 32px. "
                                        "If the icon is bigger or smaller the phone's browser will scale it and the "
                                        "image will look very pixelated.")
    colour = RGBColorField("Colour", help_text="Colour theme for the journey.")

    start_date = models.DateTimeField("Go Live On", null=True, blank=True)
    end_date = models.DateTimeField("Expire On", null=True, blank=True)
    publish_date = models.DateTimeField("Published On", null=False, blank=False, auto_now_add=True)
    modified_date = models.DateTimeField("Last Modified", null=False, blank=False, auto_now=True)

    def __unicode__(self):
        return self.name

    def is_active(self):
        if self.start_date:
            if self.start_date <= timezone.now():
                if self.end_date:
                    if self.end_date > timezone.now():
                        return True
                else:
                    return True
        return False


class Module(models.Model):

    # Accessible To
    ALL = 1
    LPS_1_4 = 2
    LPS_5 = 3

    # Percentages
    PERCENT_0 = 0
    PERCENT_25 = 25
    PERCENT_50 = 50
    PERCENT_55 = 55
    PERCENT_60 = 60
    PERCENT_65 = 65
    PERCENT_70 = 70
    PERCENT_75 = 75
    PERCENT_80 = 80
    PERCENT_85 = 85
    PERCENT_90 = 90
    PERCENT_95 = 95
    PERCENT_100 = 100

    PERCENTAGE_CHOICES = (
        (PERCENT_0, "0%"),
        (PERCENT_25, "25%"),
        (PERCENT_50, "50%"),
        (PERCENT_55, "55%"),
        (PERCENT_60, "60%"),
        (PERCENT_65, "65%"),
        (PERCENT_70, "70%"),
        (PERCENT_75, "75%"),
        (PERCENT_80, "80%"),
        (PERCENT_85, "85%"),
        (PERCENT_90, "90%"),
        (PERCENT_95, "95%"),
        (PERCENT_100, "100%")
    )

    name = models.CharField("Name", max_length=500, blank=False, unique=True)
    intro_text = models.TextField("Introductory Text", blank=True)
    end_text = models.TextField("Complete Page Text", blank=True)
    image = models.ImageField("Image", upload_to="modules/", blank=True, null=True,
                              help_text="This is an icon and the ideal size for this icon is 32 x 32px. "
                                        "If the icon is bigger or smaller the phone's browser will scale it and the "
                                        "image will look very pixelated.")
    journeys = models.ManyToManyField(
        Journey, related_name='modules', through='JourneyModuleRel',)
    accessibleTo = models.PositiveIntegerField(
        "Accessible To", choices=(
            (ALL, "All"),
            (LPS_1_4, "Learning Potential Score 1 - 4"),
            (LPS_5, "Learning Potential Score 5+")
        ),
        default=ALL)
    show_recommended = models.BooleanField("Feature in Recommended for You", default=True)
    slug = models.SlugField("Slug", unique=True, help_text="Slug used to identify this module in URL. Must be unique."
                                                           "e.g. Module_101")
    title = models.CharField("Page Title", max_length=500, blank=False,
                             help_text="Title is displayed in the browsers tab.")
    show_menu = models.BooleanField("Show in menu", default=True, help_text="Show the module link in users menu?")
    search = models.CharField("Search description", max_length=500,)
    minimum_questions = models.PositiveIntegerField("Minimum # of questions to answer",
                                                    help_text="Required number of questions to be answered to pass a "
                                                              "level.")
    minimum_percentage = models.PositiveIntegerField(
        "Minimum overall % for all questions answered", choices=PERCENTAGE_CHOICES,
        help_text="Required overall % to pass a level.")
    store_data_per_user = models.BooleanField("Data stored against User I.D.", default=True)
    start_date = models.DateTimeField("Go Live On", null=True, blank=True)
    end_date = models.DateTimeField("Expire On", null=True, blank=True)
    publish_date = models.DateTimeField("Published On", null=False, blank=False, auto_now_add=True)
    modified_date = models.DateTimeField("Last Modified", null=False, blank=False, auto_now=True)
    notified_users = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def is_active(self):
        if self.start_date:
            if self.start_date <= timezone.now():
                if self.end_date:
                    if self.end_date > timezone.now():
                        return True
                else:
                    return True
        return False

    def total_levels(self):
        return self.level_set.all().aggregate(Count('id'))['id__count']

    def get_levels(self):
        return self.level_set.all()

    def slug_intro(self):
        return "module_intro/%s" % self.slug

    def slug_home(self):
        return "module_home/%s" % self.slug

    def slug_end(self):
        return "module_end/%s" % self.slug


class JourneyModuleRel(models.Model):

    journey = models.ForeignKey(Journey)
    module = models.ForeignKey(Module)


class HarambeeJourneyModuleRel(models.Model):

    MODULE_STARTED = 0
    MODULE_HALF = 1
    MODULE_COMPLETED = 2

    MODULE_STATE_CHOICES = (
        (MODULE_STARTED, 'Active'),
        (MODULE_HALF, 'Half Way'),
        (MODULE_COMPLETED, 'Completed')
    )

    harambee = models.ForeignKey('my_auth.Harambee', null=False, blank=False)
    journey_module_rel = models.ForeignKey(JourneyModuleRel, null=False, blank=False)
    state = models.PositiveIntegerField(choices=MODULE_STATE_CHOICES, default=MODULE_STARTED)
    date_started = models.DateTimeField("Date Started", auto_now_add=True, null=True, blank=True)
    date_completed = models.DateTimeField("Date Completed", null=True, blank=True)
    last_active = models.DateTimeField("Last Active", null=True, blank=True)

    class Meta:
        verbose_name = "Harambee Module Relationship"
        verbose_name_plural = "Harambee Module Relationships"


class Level(models.Model):

    ORDERED = 0
    RANDOM = 1

    QUESTION_ORDER_CHOICES = (
        (ORDERED, "Ordered"),
        (RANDOM, "Random")
    )

    name = models.CharField("Name", max_length=500, blank=False, unique=True)
    text = models.TextField("Introductory Text", blank=True)
    module = models.ForeignKey(Module, null=True, blank=False)
    order = models.PositiveIntegerField("Level number", blank=False,
                                        help_text="Levels are completed according to this number.")
    question_order = models.PositiveIntegerField("Question Order", choices=QUESTION_ORDER_CHOICES, default=RANDOM,
                                                 help_text="Order in which questions will be chosen.")

    def __unicode__(self):
        return self.name

    def get_questions(self):
        return LevelQuestion.objects.filter(level=self)

    def get_num_questions(self):
        return self.get_questions().aggregate(Count('id'))['id__count']

    def is_active(self):
        """
            Level can only be active if it has enough questions that are in order and all questions have enough answer
            options.
        """
        enough_question = self.get_num_questions() >= self.module.minimum_questions
        if not enough_question:
            return False

        question_order_list = LevelQuestion.objects.filter(level=self).values_list('order', flat=True)
        for count in range(1, self.get_num_questions() + 1):
            if count not in question_order_list:
                return False

        all_questions = LevelQuestion.objects.filter(level=self)
        for question in all_questions:
            if not question.is_active():
                return False

        return True


class LevelQuestion(models.Model):

    name = models.CharField("Name", max_length=500, blank=False, unique=True,  default="Auto Generated")
    order = models.PositiveIntegerField("Order Number", blank=False, help_text="Order number determines the order in "
                                                                               "which questions are asked in a level.")
    level = models.ForeignKey(Level, null=True, blank=False)
    question_content = models.TextField("Question", blank=False)
    notes = models.TextField("Additional Notes", blank=True)
    image = models.ImageField("Image", upload_to="questions/", blank=True, null=True,
                              help_text="This is an image and the ideal size for this image should be 150px in width. "
                                        "If the image width is bigger or smaller the phone's browser "
                                        "will scale it and the image will look very pixelated.")

    def __unicode__(self):
        return self.name

    def is_active(self):
        """
            Question is active if it has more than 2 answer options.
        """

core/models.py
from django.db import models


class Page(models.Model):
    slug = models.SlugField()
    title = models.CharField("Page Title", max_length=50, blank=False,
                             help_text="Title text appears on the browsers tab.")
    heading = models.CharField("Page Heading", max_length=50, blank=False,
                               help_text="Heading text appears on the page.")
    content = models.TextField("Page Content", blank=True)

    def __unicode__(self):
        return self.heading


class HelpPage(Page):
    show = models.BooleanField("Show in menus")
    description = models.TextField("Search Description")
    activate = models.DateTimeField("Go live date/time", null=True, blank=True)
    deactivate = models.DateTimeField("Expiry date/time", null=True, blank=True)

    class Meta:
        verbose_name = "Help Page"
        verbose_name_plural = "Help Pages"

harambee/templates/core/main.html
<!DOCTYPE html>
<html>
    <head>
        <title>HARAMBEE MOBILE | {% block title %}{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static "/static/css/harambee.css" %}">
        <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/favicon.ico?v=2" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <script type="text/javascript" src="//www.google.com/jsapi"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery.js"></script>
        <script type="text/javascript" src="{% static "/static/js/header.js" %}"></script>
    </head>
    <body>
        {% load google_analytics_tags %}
        <div style="display:none">
            <img src="{% google_analytics request %}" width="0" height="0" />
        </div>

        <div class="header {% if header_colour %}{{ header_colour }}{% else %}green-back{% endif %}" id="header">
            <div class="header-container" id="header-container">
                <div class="icon-container" id="icon-container">
                    <div class="icons" id="icons">
                        <a class="menu-icon" href="{% if user.id %}/home{% else %}/{% endif %}"><img src="/static/img/icn_logo_white_small.png"></a>
                        <a class="menu-link" id="menu-link" {% if user.id %}href="/menu">MENU{% else %}href="/login">LOG IN{% endif %}</a>
                    </div>
                </div>
                {% if hide == False %}
                    <div class="title-container" id="title-container">
                        <div class="title-text">
                            <p class="large-font white-front {% if header_colour %}{{ header_colour }}{% else %}black-back{% endif %}">
                                {% block header %}{% endblock %}
                            </p>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>

        {% block search%}
        {% endblock %}

        {% block menu %}
        {% endblock %}

        <div id="footer" class="footer">
            <p>Brought to you by Harambee Youth</p>
            <p class="margin-bot-10">Employment Accelerator.</p>
            <div>
                <a href="/terms">Terms</a> |
                <a href="/about">About</a> |
                <a href="/contact">Contact</a> |
                <a href="http://harambee.mobi">Website</a>
            </div>
        </div>

        {% if request.session.user.id %}
            {% block menu_feature %}
                {% include "core/menu.html" %}
            {% endblock %}
        {% endif %}
    </body>
</html>

harambee/templates/core/main_menu.html
{% extends "core/main.html" %}

{% block title %}MENU{% endblock %}

{% block menu %}
    {% include "core/menu.html" %}
{% endblock %}

{% block menu_feature %}
{% endblock %}

harambee/templates/core/main_search.html
<div id="search-container" class="search-container black-back">
    <div class="box-border">
        <form action="/search/" method="get">
            {% csrf_token %}
            <div class="search-box">
                <input type="text" name="q" id="id_search" placeholder="SEARCH" class="search-text black-back white-front no-border"/>
                <div class="search-go">
                    <input type="image"  src="/static/img/icn_search_white_small.png" value="GO" class="black-back white-front no-border"/>
                </div>
            </div>
        </form>
    </div>
</div>

harambee/templates/core/menu.html
{% block content %}

    <div id="menu" class="menu">
        <a href="/logout"><div class="item text"><li class="icon logout"></li><p>LOG OUT</p></div></a>
        <a href="/profile/"><div class="item text"><li class="icon profile"></li><p>MY PROFILE</p></div></a>
        <a href="/home"><div class="item text"><li class="icon home"></li><p>HOME</p></div></a>
        {% for journey in journeys %}
            {% if journey.image %}
                <a href="/journey_home/{{ journey.slug }}"><div class="item text"><li class="icon" {% if journey.image %}style="background-image: url('{{ journey.image.url }}'); background-size: 50px;"{% endif %}></li><p>{{ journey.name|upper }}</p></div></a>
            {% else %}
                <a href="/journey_home/{{ journey.slug }}"><div class="item text"><li class="icon default"></li><p>{{ journey.name |upper }}</p></div></a>
            {% endif %}
        {% endfor %}
        <a href="/search"><div class="item text"><li class="icon search"></li><p>SEARCH</p></div></a>
        <a href="/help"><div class="item text"><li class="icon help"></li><p>HELP</p></div></a>
        <a href="/about"><div class="item text"><li class="icon about"></li><p>ABOUT</p></div></a>
    </div>

{% endblock %}